### ISSUE TITLE
Move/Remove 'Select BOINC projects' from pool guide

### ISSUE THREAD

**Issue by grctest** [grctest/Gridcoin-Site#47]
https://www.reddit.com/r/gridcoin/comments/6k10bt/step_1b_at_httpwwwgridcoinusguidespoolhtm_may/

> I believe when seeing "Choose BOINC projects from the whitelist", many people will understand it as choosing a project to join at BOINC client software based on the white list, which should not be done if participating pool mining.
>
> As I mentioned in this post (https://www.reddit.com/r/gridcoin/comments/6hvm5f/i_needs_to_be_emphasized_that_the_crunchers/), project should be added by syncing with the pool account manager.

Perhaps worth moving step 1B to 1C, or should it just be entirely removed?

**Comment by silent5am** [comment]
No, 1B is fine, it just needs to be after 1C and/or part of 1C. 

For pool crunching, ppl first should register with the pool, then select a project from the pool's whitelist while logged in in their pool account, then sync with BOINC manager.

I'd basically just write a short transcript of the grcpool videos - so ppl can read the basic steps and if they still don't get it they can watch the videos.
_____
About Katiee's pool: is this still working?

In general I would not make suggestions such as "If I had to pick between the two pools, I'd use ..." because that's not really our place to do imho. It's the project's main hub as far as I understand, so it should be neutral and just display all options currently avaiable.

However, what we could implement is some sort of "pool status" - similar to [game server status](http://www.wowrealmstatus.net/), e.g. green dot for "pool up and running", yellow dot for "pool semi-active", orange dot for "maintenance/offline" or I don't know. 

As for Katiee's pool: would it be possible to take it over from Katiee?

**Comment by grctest** [comment]
Removed the pool suggestion, reworked the partials to move the project selection around, pushed to production. Thanks 👍
